### ISSUE TITLE
ALTER TABLE fails to be parsed

### ISSUE THREAD

**Issue by kolbitsch-lastline** [pingcap/parser#1017]
> 1. What did you do?

When I create a test table using the following definition:

```
MariaDB [metadata]> create table mytable (`error` varchar(255) DEFAULT NULL);
Query OK, 0 rows affected (0.06 sec)

MariaDB [metadata]> show create table mytable;
+---------+---------------------------------------------------------------------------------------------------+
| Table   | Create Table                                                                                      |
+---------+---------------------------------------------------------------------------------------------------+
| mytable | CREATE TABLE `mytable` (
  `error` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 |
+---------+---------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

I can successfully alter this table using the following 2 commands:

```
MariaDB [metadata]> ALTER TABLE `mytable` CHANGE COLUMN `error` `error` varchar(127) DEFAULT NULL;
Query OK, 0 rows affected (0.23 sec)               
Records: 0  Duplicates: 0  Warnings: 0

MariaDB [metadata]> ALTER TABLE `mytable` CHANGE COLUMN error error varchar(127) DEFAULT NULL;
Query OK, 0 rows affected (0.01 sec)
Records: 0  Duplicates: 0  Warnings: 0
```

However, parsing the last statement (which is valid according to the above example), fails to be parsed:

```
parser := sqlParser: parser.New()
sql := "ALTER TABLE `mytable` CHANGE COLUMN error error varchar(127) DEFAULT NULL"
stmts, _, err := parser.Parse(sql, "", "")
```

> 2. What did you expect to see?

statement is parsed correctly, returning the statement/tokens/AST of the `ALTER` SQL command

> 3. What did you see instead?

an error in `err` is returned saying `line 1 column 41 near "error error varchar(127) DEFAULT NULL"`

Interestingly, when modifying the `sql` variable contents to be

```
sql := "ALTER TABLE `mytable` CHANGE COLUMN `error` `error` varchar(127) DEFAULT NULL"
```

we succeed at parsing it. Seems the `error` string without quotes is throwing off the parser

4. What version of TiDB SQL Parser are you using?

```
commit 635dd473fca2587243f1d6012e73290cfce95851 (HEAD -> master, origin/master, origin/HEAD)
Author: bb7133 <bb7133@gmail.com>
Date:   Mon Feb 24 15:39:21 2020 +0800
```

**Comment by xhebox** [comment]
I believe it is solved by https://github.com/pingcap/parser/commit/fa890576392898d7fbc913900ae0d5e7b586bb3c. The master branch should work as expected.

**Comment by kolbitsch-lastline** [comment]
indeed! I was able to reproduce and confirm the bug is fixed in that commit :+1: 

thanks a ton for following up so quickly
