### ISSUE TITLE
FuncCallExpr Restore format

### ISSUE THREAD

**Issue by cposture** [pingcap/parser#1070]
## Feature Request

**Is your feature request related to a problem? Please describe:**

I recently wanted to use the restore function to perform a mysql diff tool, but the difference in format caused diff fail

**Describe the feature you'd like:**

got: `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() 
want: `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP

the got CURRENT_TIMESTAMP with a pair of parentheses，Can this pair of brackets be optional？

mysql document：https://dev.mysql.com/doc/refman/5.6/en/timestamp-initialization.html

**Comment by cposture** [comment]
@tangenta

**Comment by bb7133** [comment]
Thanks for reporting, Looks that they are the same:

> Any of the synonyms for CURRENT_TIMESTAMP have the same meaning as CURRENT_TIMESTAMP. These are CURRENT_TIMESTAMP(), NOW(), LOCALTIME, LOCALTIME(), LOCALTIMESTAMP, and LOCALTIMESTAMP().

So I think it should be fine, can you ignore this diff?

**Comment by cposture** [comment]
ok
