### ISSUE TITLE
Support of call query

### ISSUE THREAD

**Issue by GoWebProd** [pingcap/parser#1073]
Hello, does this parser support MySQL call query? https://dev.mysql.com/doc/refman/5.6/en/call.html

I receive error:

`line 1 column 4 near "call test(1, '2', true);"`

**Comment by kennytm** [comment]
Not yet, since TiDB does not support stored procedures.

Contributors are welcome to support *parsing* these statements though.

**Comment by nullnotnil** [comment]
Fixed in https://github.com/pingcap/parser/pull/1077
