### ISSUE TITLE
Support missing charsets

### ISSUE THREAD

**Issue by lechuckroh** [pingcap/parser#1140]
## Feature Request

MySQL supported charsets: https://dev.mysql.com/doc/refman/8.0/en/charset-charsets.html

parser supported charsets: https://github.com/pingcap/parser/blob/master/charset/charset.go#L55-L61

I get a parse error if I use unsupported charset:
```sql
CREATE TABLE `message` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `msg` text DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=euckr;
```

Error message:
```
[parser:1115]Unknown character set: 'euckr'
```

**Comment by bb7133** [comment]
Hi, thanks for reporting!

BTW, do you want "`euckr`" to be supported by TiDB, or just the parser(able to parse it, but reports an error in TiDB server)?

**Comment by winkyao** [comment]
@lechuckroh hi, do you have any interest to contribute? you can join the slack of the SIG channel(sig-sql-infra) via: https://slack.tidb.io/invite?team=tidb-community&channel=sig-sql-infra

**Comment by lechuckroh** [comment]
@bb7133 
I'm using just the parser in my application.

Will TiDB have any problem if new charset is added to parser only?

**Comment by bb7133** [comment]
Got it!

Probably we need additional check for TiDB but it should be simple and reasonable.
