### ISSUE TITLE
Is there any interface/settings that could let parser ignore some statement?

### ISSUE THREAD

**Issue by joway** [pingcap/parser#1183]
## Question

Hi, thanks for creating such a great SQL parser!

We want to use this parser to do some analysis job in our real-time services but found it cause some performance issues.

In our cases, we just want to get table names from the user's SQL query, but the parser still needs to parse all AST nodes which increases unnecessary CPU times. As I think if we could ignore some parse process like the `WHERE` statement, it could have a lot of performance improvements.

Is there any interface/settings that could let us control the parser behavior or let it ignore some statement?

Our usage like this:

```golang
var astVisitorPool = sync.Pool{
	New: func() interface{} {
		return &astVisitor{
			parser: parser.New(),
			tables: map[string]struct{}{},
			method: "",
		}
	},
}

type astVisitor struct {
	parser *parser.Parser
	tables map[string]struct{}
	method string
}

func (v *astVisitor) Enter(in ast.Node) (out ast.Node, skipChildren bool) {
	switch stmt := in.(type) {
	case *ast.SelectStmt:
		v.setMethod("SELECT")
	case *ast.DeleteStmt:
		v.setMethod("DELETE")
	case *ast.InsertStmt:
		v.setMethod("INSERT")
	case *ast.UpdateStmt:
		v.setMethod("UPDATE")
	case *ast.TableName:
		v.tables[stmt.Name.String()] = struct{}{}
	}
	return in, false
}

func (v *astVisitor) Leave(in ast.Node) (out ast.Node, ok bool) {
	return in, true
}
```

By the way, `Enter(in ast.Node) (out ast.Node, skipChildren bool)` function just could control the AST node vistor but cannot control the `Parse`. So `skipChildren` cannot help in this case.

**Comment by lfkdsk** [comment]
this parser is written by lexer & yacc - like parser-generate.

**Comment by tangenta** [comment]
> I don't think there is any way to get the internal result from this tool.

+1. If you want to skip some statements, you can delete some unnecessary rules or semantic actions in `parser.y`. BTW, currently we don't have the bench framework to measure the performance of parser :(

**Comment by joway** [comment]
As a solution to solve the performance issues for our use case, we use `NormalizeDigest` to get the digest as the cache key :

```
_, hash := parser.NormalizeDigest(sql)
if result, ok := v.cache[hash]; ok {
    return result
} else {
    v.cache[hash] = &parserResult{}
}
```
