### ISSUE TITLE
Is there an easy way to construct a node?

### ISSUE THREAD

**Issue by guidao** [pingcap/parser#1187]
## Question
I would like to implement the following functions.
select * from a where id = 1;
==>
select * from a where id = 1 and tenant_id = “xxxx” and …. more

*Is there an easy way to construct a ast node?*

**Comment by kennytm** [comment]
doing something like 

```go
expr = &ast.BinaryOperatorExpr {
    Op: opcode.LogicAnd,
    L: expr,
    R: /* fill in yourself */
}
```

should work.

**Comment by guidao** [comment]
This structure is a bit complicated when there are a lot of fields to change. It would be much easier to have the quote, unquote operators in other languages. (For example: https://elixir-lang.org/getting-started/meta/quote-and-unquote.html in elixir)

**Comment by kennytm** [comment]
Forward that complain to Go's language designers 😅 (actually don't, being explicit and wordy is a goal of Go.)
