### ISSUE TITLE
Some CTE statement is parse wrongly

### ISSUE THREAD

**Issue by wjhuang2016** [pingcap/parser#1218]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
``` sql
with cte as (select 1) select 1 union with cte as (select 1) select * from cte;
with cte as (select 1) (select 1);
with cte as (select 1) (select 1 union select 1);
select * from (with cte as (select 1) select 1 union select 2) qn;
select * from t where 1 > (with cte as (select 2) select * from cte);
( with cte(n) as ( select 1 ) select n+1 from cte union select n+2 from cte) union select 1;
( with cte(n) as ( select 1 ) select n+1 from cte) union select 1;
( with cte(n) as ( select 1 ) (select n+1 from cte)) union select 1;
```

2. What did you expect to see?

The same as MySQL

3. What did you see instead?
Inconsistent with MySQL

4. What version of TiDB SQL Parser are you using?

master

**Comment by tisonkun** [comment]
subtask of  https://github.com/pingcap/tidb/issues/17472
