### ISSUE TITLE
wrong ast node type when parse `alter table add key...` 

### ISSUE THREAD

**Issue by Ehco1996** [pingcap/parser#1263]
## questions

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
main.go

```go
package main

import (
	"fmt"

	"github.com/pingcap/parser"
	_ "github.com/pingcap/tidb/types/parser_driver"
)

func main() {
	p := parser.New()

	sql := "ALTER TABLE `online_ddl`.`_t2_new` add key name (name)"
	stmtNodes, _, err := p.Parse(sql, "", "")

	if err != nil {
		fmt.Printf("parse error:\n%v\n%s", err, sql)
		return
	}
	for _, stmtNode := range stmtNodes {
		fmt.Printf("%#v \n", stmtNode)
	}
}
```

2. What did you expect to see?

i am not sure if the node type shoule be `CreateIndexStmt`

3. What did you see instead?
```
&ast.AlterTableStmt{ddlNode:ast.ddlNode{stmtNode:ast.stmtNode{node:ast.node{text:"ALTER TABLE `online_ddl`.`_t2_new` add key name (name)", offset:0}}}, Table:(*ast.TableName)(0xc000156a00), Specs:[]*ast.AlterTableSpec{(*ast.AlterTableSpec)(0xc0001721c0)}}
```

4. What version of TiDB SQL Parser are you using?

`github.com/pingcap/parser v0.0.0-20200623082809-b74301ac298b/go.mod h1:vQdbJqobJAgFyiRNNtXahpMoGWwPEuWciVEK5A20NS0=
`

**Comment by kennytm** [comment]
Since ALTER TABLE ADD [INDEX | KEY] and CREATE INDEX are semantically equivalent I don't see any problem of them being conflated to the same AST type.

**Comment by Ehco1996** [comment]
@kennytm 

The return type of the parser is `AlterTableStmt`, but I think it should be `CreateIndexStmt` because the semantics of `create index` and `alter table add key` are the same.

**Comment by kennytm** [comment]
well it's the same as the treatment of [MySQL 8](https://dev.mysql.com/doc/refman/8.0/en/create-index.html), as ALTER TABLE ADD KEY is more powerful than CREATE INDEX

> `CREATE INDEX` is mapped to an `ALTER TABLE` statement to create indexes. See Section 13.1.9, “`ALTER TABLE` Statement”. `CREATE INDEX` cannot be used to create a `PRIMARY KEY`; use `ALTER TABLE` instead. For more information about indexes, see Section 8.3.1, “How MySQL Uses Indexes”.

**Comment by tangenta** [comment]
@Ehco1996 Can we close this issue now?
