### ISSUE TITLE
is there any easy to change the select field?

### ISSUE THREAD

**Issue by cjphaha** [pingcap/parser#1285]
for example:
The original sql statement is:
```sql
SELECT  name, user, password  FROM info;
```
I want to convert it to:
```sql
SELECT  name,user,password_encrypted  FROM info;
```

how to change the password field to password_encrypted? i need help, thx!

**Comment by cjphaha** [comment]
I tried to use setTest but failed
```go
type FingerprintVisitor struct{}

func (f *FingerprintVisitor) Enter(in ast.Node) (node ast.Node, skipChildren bool) {
	if v, ok := in.(*ast.SelectField);ok {
		v.SetText("replaced_num")
	}
	return in, false
}

func (f *FingerprintVisitor) Leave(in ast.Node) (node ast.Node, ok bool) {
	return in, true
}
```

**Comment by tangenta** [comment]
```go
func (f *FingerprintVisitor) Enter(in ast.Node) (node ast.Node, skipChildren bool) {
	if sf, ok := in.(*ast.SelectField); ok {
		if cn, ok := sf.Expr.(*ast.ColumnNameExpr); ok {
			if cn.Name.Name.L == "password" {
				cn.Name.Name = model.NewCIStr("password_encrypted")
			}
		}
	}
	return in, false
}
```

@cjphaha You can check the rules in the `parser.y` to peek at the possible structs.

**Comment by cjphaha** [comment]
> ```go
> func (f *FingerprintVisitor) Enter(in ast.Node) (node ast.Node, skipChildren bool) {
> 	if sf, ok := in.(*ast.SelectField); ok {
> 		if cn, ok := sf.Expr.(*ast.ColumnNameExpr); ok {
> 			if cn.Name.Name.L == "password" {
> 				cn.Name.Name = model.NewCIStr("password_encrypted")
> 			}
> 		}
> 	}
> 	return in, false
> }
> ```
> 
> @cjphaha You can check the rules in the `parser.y` to peek at the possible structs.

thx!

**Comment by cjphaha** [comment]
> ```go
> func (f *FingerprintVisitor) Enter(in ast.Node) (node ast.Node, skipChildren bool) {
> 	if sf, ok := in.(*ast.SelectField); ok {
> 		if cn, ok := sf.Expr.(*ast.ColumnNameExpr); ok {
> 			if cn.Name.Name.L == "password" {
> 				cn.Name.Name = model.NewCIStr("password_encrypted")
> 			}
> 		}
> 	}
> 	return in, false
> }
> ```
> 
> @cjphaha You can check the rules in the `parser.y` to peek at the possible structs.

Sorry, I have another question to consult you, is there easy way totransfer this insert sql 
```sql
INSERT INTO `account` (`name`,`password_plain`) VALUES (?,?)
```
to 
```sql
INSERT INTO `account` (`name`,`password`, `password_plain`, `password_enctryped`) VALUES (?,?)
```

**Comment by tangenta** [comment]
Please take a look at `InsertStmt.Columns`. You can use a similar visitor to change it.

**Comment by cjphaha** [comment]
> Please take a look at `InsertStmt.Columns`. You can use a similar visitor to change it.

thank you very very much!
