### ISSUE TITLE
Invalid characters generated by goyacc?

### ISSUE THREAD

**Issue by jackysp** [pingcap/parser#1320]
## Question

Invalid characters generated by goyacc?

<img width="453" alt="截屏2021-08-21 下午6 35 08" src="https://user-images.githubusercontent.com/4352397/130319319-ceb1b312-d65f-47fe-ab30-d5f1b5d6bc8e.png">

happened in 48d84c1db4287c2649f9a38b3b23a55c4bd528b5

**Comment by freeman983** [comment]
@jackysp 
I get the same problem in version 1.17, it is normal to use 1.16. I guess it may be related to this change in 1.17:

The Writer.WriteRune method now writes the replacement character U+FFFD for negative rune values, as it does for other invalid runes.

**Comment by jackysp** [comment]
https://github.com/pingcap/tidb/pull/29846 fixed it in TiDB repo. @freeman983
