### ISSUE TITLE
How to beautify sql with this package ?

### ISSUE THREAD

**Issue by clearcodecn** [pingcap/parser#1374]

**Comment by tangenta** [comment]
You can parse the SQL and restore it from an AST:

```go
package main

import (
	"fmt"
	"strings"

	"github.com/pingcap/tidb/parser"
	"github.com/pingcap/tidb/parser/format"
	_ "github.com/pingcap/tidb/parser/test_driver"
)

func main() {
	p := parser.New()
	fmt.Println(beautify(p, "SeleCT  a, b from    t where ((c = 1));"))
}

func beautify(p *parser.Parser, sql string) string {
	stmt, _, err := p.ParseSQL(sql)
	if err != nil {
		panic(err)
	}
	var sb strings.Builder
	ctx := format.NewRestoreCtx(format.DefaultRestoreFlags, &sb)
	err = stmt[0].Restore(ctx)
	if err != nil {
		panic(err)
	}
	return sb.String()
}

```

**Comment by clearcodecn** [comment]
thanks.

**Comment by morlay** [comment]
But `github.com/pingcap/tidb/parser` couldn't `go get`
May consider remove this file https://github.com/pingcap/tidb/blob/master/parser/go.mod

**Comment by sunyaf** [comment]
> You can parse the SQL and restore it from an AST:
> 
> ```go
> package main
> 
> import (
> 	"fmt"
> 	"strings"
> 
> 	"github.com/pingcap/tidb/parser"
> 	"github.com/pingcap/tidb/parser/format"
> 	_ "github.com/pingcap/tidb/parser/test_driver"
> )
> 
> func main() {
> 	p := parser.New()
> 	fmt.Println(beautify(p, "SeleCT  a, b from    t where ((c = 1));"))
> }
> 
> func beautify(p *parser.Parser, sql string) string {
> 	stmt, _, err := p.ParseSQL(sql)
> 	if err != nil {
> 		panic(err)
> 	}
> 	var sb strings.Builder
> 	ctx := format.NewRestoreCtx(format.DefaultRestoreFlags, &sb)
> 	err = stmt[0].Restore(ctx)
> 	if err != nil {
> 		panic(err)
> 	}
> 	return sb.String()
> }
> ```

why THE result WITHOUT \n
