### ISSUE TITLE
Help to explain a little bit the meaning of the SubqueryExpr.

### ISSUE THREAD

**Issue by doggeral** [pingcap/parser#145]
Hi TiDB team,
I'd like to work on the SubqueryExpr task but I'm confusing on the meaning of the [SubqueryExpr](https://github.com/pingcap/parser/blob/master/ast/expressions.go#L337-L345). Can you help to add some comments or give some example to explain?

Thanks!

**Comment by winoros** [comment]
What kind of information do you want to know?
`SubqueryExpr` means a subquery in SQL. e.g. `select * from t where t.a in (select b from t2)`, `select b from t2` is a `SubqueryExpr` in the AST generated from this SQL.

**Comment by doggeral** [comment]
Thanks for your example @winoros . Per the [subquery syntax](https://dev.mysql.com/doc/refman/5.7/en/subqueries.html) doc, I know the meaning of [Correlated](https://github.com/pingcap/parser/blob/master/ast/expressions.go#L342), [Exists](https://github.com/pingcap/parser/blob/master/ast/expressions.go#L344). But I can't find any explaination on Evaluated and MultiRows.

**Comment by winoros** [comment]
@doggeral Our ast structure is not totally the same with MySQL's. I'll prepare an explanation for you.

**Comment by doggeral** [comment]
@wangbo got it, thanks!
