### ISSUE TITLE
Support CREATE USER extensions per MySQL 5.7

### ISSUE THREAD

**Issue by morgo** [pingcap/parser#158]
Via https://github.com/pingcap/tidb/issues/7733 - this command does not currently work in TiDB:
```
mysql> CREATE USER 'msandbox'@'localhost' IDENTIFIED WITH 'mysql_native_password' AS '*6C387FC3893DBA1E3BA155E74754DA6682D04747' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK;
ERROR 1105 (HY000): line 1 column 129 near " NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK" (total length 173)
```

MySQL 5.7 produces this result from the command `SHOW CREATE USER`, so it is important to parse and the unsupported parts could probably be ignored for now.

**Comment by spongedu** [comment]
@morgo I'm working on this.

**Comment by morgo** [comment]
Awesome, thank you!
