### ISSUE TITLE
incompatible with MySQL when calculate display length of numeric type 

### ISSUE THREAD

**Issue by bytewatch** [pingcap/parser#16]
# Problem
When parsing ddl, and when no Flen assigned, TiDB's parse result is not compatible with MySQL.

These are types  after  ddl executed by MySQL 5.7:
* tinyint(3) unsigned
* smallint(5) unsigned
* mediumint(8) unsigned
* int(10) unsigned

These are types after parsed by TiDB parser: 
* tinyint(4) unsigned
* smallint(6) unsigned
* mediumint(9) unsigned
* int(11) unsigned

# Cause
Because func `FieldType.CompactStr()` in file types/field_type.go  doesn't take account the sign of numeric.

# Fix
Refer souce of MySQL 5.7, take account the sign of numeric, when calculate default field length.

**Comment by bytewatch** [comment]
have a look at PR #17

**Comment by tiancaiamao** [comment]
PTAL @zimulala @winkyao

**Comment by tangenta** [comment]
Already fixed by pingcap/tidb#4693.
