### ISSUE TITLE
Alter table restore incorrect 

### ISSUE THREAD

**Issue by mia0x75** [pingcap/parser#176]
sql:
alter table t1 add c1 int  comment 'c1',
add c2 decimal (4,1) not null comment 'c2',
add c3 decimal (4,1) not null default  0.0 comment 'c3';

restore:
ALTER TABLE `t1` ADD COLUMN `c1` INT COMMENT 'c1', ADD COLUMN `c2` DECIMAL(4,1) NOT NULL, COMMENT 'c2', ADD COLUMN `c3` DECIMAL(4,1) NOT NULL, DEFAULT 0.0, COMMENT 'c3'

expected:
ALTER TABLE `t1` ADD COLUMN `c1` INT COMMENT 'c1', ADD COLUMN `c2` DECIMAL(4,1) NOT NULL COMMENT 'c2', ADD COLUMN `c3` DECIMAL(4,1) NOT NULL DEFAULT 0.0 COMMENT 'c3'

**Comment by kennytm** [comment]
The diff for easy inspection:

```diff
-ALTER TABLE `t1` ADD COLUMN `c1` INT COMMENT 'c1', ADD COLUMN `c2` DECIMAL(4,1) NOT NULL COMMENT 'c2', ADD COLUMN `c3` DECIMAL(4,1) NOT NULL DEFAULT 0.0 COMMENT 'c3'
+ALTER TABLE `t1` ADD COLUMN `c1` INT COMMENT 'c1', ADD COLUMN `c2` DECIMAL(4,1) NOT NULL, COMMENT 'c2', ADD COLUMN `c3` DECIMAL(4,1) NOT NULL, DEFAULT 0.0, COMMENT 'c3'
```

**Comment by leoppro** [comment]
fixed now, you can test it at master.
