### ISSUE TITLE
CURRENT_TIMESTAMP FuncCallExpr should support args

### ISSUE THREAD

**Issue by Ryan-Git** [pingcap/parser#186]
like the question on so :https://stackoverflow.com/questions/23671222/mysql-default-value-for-timestamp3

> mysql> create table tbl_so_q23671222_1( ts timestamp(3) default now() );
ERROR 1067 (42000): Invalid default value for 'ts'
mysql> create table tbl_so_q23671222_1( ts timestamp(3) default now(3) );
Query OK, 0 rows affected (0.59 sec)
mysql> create table tbl_so_q23671222_2( ts timestamp(3) default current_timestamp );
ERROR 1067 (42000): Invalid default value for 'ts'
mysql> create table tbl_so_q23671222_2( ts timestamp(3) default current_timestamp(3) );
Query OK, 0 rows affected (0.38 sec)

current_timestamp(**3**) should be parsed, otherwise it's not a valid ddl. 

version: 5958b6fcdb2d33614d9b2ab99f76b5c1c422b39f

example: 
```go
func TestDDL(t *testing.T) {
	s := `create table t(dt datetime(6) not null default current_timestamp(6) on update current_timestamp(6))`
	p := parser.New()
	stmt, err := p.ParseOneStmt(s, "", "")
	require.NoError(t, err)
	b := bytes.NewBufferString("")
	ctx := format.NewRestoreCtx(format.DefaultRestoreFlags, b)
	require.NoError(t, stmt.Restore(ctx))
	fmt.Println(b.String())
}
```
 outputs 
```sql
`CREATE TABLE `t` (`dt` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP())` 
```
which is invalid.

**Comment by spongedu** [comment]
I think we should move this issue to `TiDB` repo.

**Comment by spongedu** [comment]
@zz-jason

**Comment by zz-jason** [comment]
> I think we should also add an issue in `TiDB` repo, too. Checks should be done in ddl.

Agreed. In this parser issue, let's focused on the problem that `current_timestamp(3)` is not parsed problem.

**Comment by Ryan-Git** [comment]
thx

**Comment by Ryan-Git** [comment]
it's not completely resolved. 
`ON UPDATE CURRENT_TIMESTAMP()` should be `ON UPDATE CURRENT_TIMESTAMP(6)`
`NowSymOptionFraction` in `ON UPDATE` `ColumnOption` should add args, too.
