### ISSUE TITLE
How to get comment info in SelectStmt?

### ISSUE THREAD

**Issue by loxp** [pingcap/parser#239]
## Question

After parsing a SELECT SQL successfully, how to get comment info in SelectStmt? like this:

```
/* this is a comment */ SELECT * from tbl;
```

**Comment by kennytm** [comment]
Comments (except `/*! ... */` and `/*+ ... */`) are dropped during tokenization. There's no way to recover it from AST. Perhaps you could parse the original string instead.

**Comment by loxp** [comment]
> Comments (except `/*! ... */` and `/*+ ... */`) are dropped during tokenization. There's no way to recover it from AST. Perhaps you could parse the original string instead.

OK, thanks.

**Comment by whizkid77** [comment]
Any easy way to include it in tokenization?  Like a new type `CommentNode` or something?
