### ISSUE TITLE
decouple Assignment and ColumnName

### ISSUE THREAD

**Issue by loxp** [pingcap/parser#244]
## Feature Request

Currently, the Assignment holds the *ColumnName directly,

```
type Assignment struct {
	node
	// Column is the column name to be assigned.
	Column *ColumnName
	// Expr is the expression assigning to ColName.
	Expr ExprNode
}
```

Is it possible to hold the *ColumnNameExpr instead of *ColumnName? We use the UpdateStmt and want to decorate the column names in Assignment, but it is coupled with *ColumnName now.

**Comment by winkyao** [comment]
@XuHuaiyu PTAL
