### ISSUE TITLE
Support CTEs (WITH statement)

### ISSUE THREAD

**Issue by tlightsky** [pingcap/parser#289]
## Feature Request

any plan to support with clause from SQL:1999 and supported by MySQL 8.0

https://dev.mysql.com/doc/refman/8.0/en/with.html#common-table-expressions-syntax

**Comment by morgo** [comment]
@tlightsky Thank you for the feature request. CTEs are currently [on the roadmap](https://pingcap.com/docs/ROADMAP/).

**Comment by tlightsky** [comment]
@morgo thanks for reply
need this feature recently, 
maybe i can make a pr when i finish it,
is there any hint that i can add it quickly?
(maybe just point out where i should make changes)

**Comment by tlightsky** [comment]
i have do some work about [adding CTEs (WITH statement)](https://github.com/tlightsky/parser/commit/bdbb51e607f739e49030d40f964848c2dd4dee96),
need some help to fix failed tests

**Comment by zz-jason** [comment]
@tlightsky Common Table Expression is a huge feature, we need a detailed discuss and design document about it.

**Comment by zz-jason** [comment]
I've created a github project to trace the progress: https://github.com/pingcap/tidb/projects/21

**Comment by tlightsky** [comment]
@zz-jason 
thanks for response,

Currently, my plan is to parse it to ast tree(without recursive),
then expand those `CTEs` to form a SQL without `WITH Statement`,
so i can use `WITH Statement` in platforms like MySQL 5.7, Clickhouse

Also noticed OceanBase support non-recursive CTEs by [only expanding them](https://mp.weixin.qq.com/s/iUqpv_eK91mb6KassdcR3g) too,
would be nice to have CTEs support in TiDB even only just expand those subqueries

**Comment by kyleconroy** [comment]
Is this still on the roadmap? I don't need CTE support in TiDB, just in the parser.

**Comment by kennytm** [comment]
yes, compatibility with mysql 8 is always desirable.

(you may also want to follow pingcap/tidb#17472 for the overall roadmap of CTE support in TiDB, which drives the parser implementation.)

**Comment by zz-jason** [comment]
> Is this still on the roadmap? I don't need CTE support in TiDB, just in the parser.

@kyleconroy Oh, seems you are using this parser as a library in a project. May I know your use scenarios?

**Comment by wjhuang2016** [comment]
Supported by https://github.com/pingcap/parser/pull/1207
/cc @tlightsky @kyleconroy
