### ISSUE TITLE
Parser example doesn't work

### ISSUE THREAD

**Issue by CrazyNash** [pingcap/parser#320]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

I am trying this out according to https://godoc.org/gopkg.in/lysu/parser.v1#example-package--ParseSQL

```
package main

import (
    "fmt"

    "github.com/pingcap/parser"
    _ "github.com/pingcap/tidb/types/parser_driver"
)

func main() {

    // 0. make sure import parser_driver implemented by TiDB(user also can implement own driver by self).
    // and add `import _ "github.com/pingcap/tidb/types/parser_driver"` in the head of file.

    // 1. Create a parser. The parser is NOT goroutine safe and should
    // not be shared among multiple goroutines. However, parser is also
    // heavy, so each goroutine should reuse its own local instance if
    // possible.
    p := parser.New()

    // 2. Parse a text SQL into AST([]ast.StmtNode).
    stmtNodes, _, err := p.Parse("select * from tbl where id = 1", "", "")

    // 3. Use AST to do cool things.
    fmt.Println(stmtNodes[0], err)

}

```
```
$ go build main.go
go: finding github.com/pingcap/tidb/types/parser_driver latest
go: finding github.com/pingcap/tidb/types latest
build command-line-arguments: cannot load github.com/pingcap/tidb/types/parser_driver: cannot find module providing package github.com/pingcap/tidb/types/parser_driver
```

2. What did you expect to see?

build success

3. What did you see instead?

Can't find package

4. What version of TiDB SQL Parser are you using?

Not sure, the latest?

**Comment by CrazyNash** [comment]
I fixed this by replacing default mod requirements for tidb by 

```
	github.com/pingcap/tidb v0.0.0-20190321025159-e8299209340c
	github.com/pingcap/tipb v0.0.0-20190107072121-abbec73437b7
```

**Comment by leoppro** [comment]
update the tidb like this:
`go get -u github.com/pingcap/tidb@master`
and you may get this error:
`go: github.com/golang/lint@v0.0.0-20190313153728-d0100b6bd8b3: parsing go.mod: unexpected module path "golang.org/x/lint"`

see:https://github.com/golang/go/wiki/Resolving-Problems-From-Modified-Module-Path

**Comment by tangenta** [comment]
@leoppro 
`go get github.com/pingcap/tidb/types/parser_driver@master` is enough for building.
