### ISSUE TITLE
parser crashes when given comments

### ISSUE THREAD

**Issue by suzaku** [pingcap/parser#330]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

`parser.ParseOneStmt("/*!SET;SET;*/")`

2. What did you expect to see?

Parsed the comment correctly or return error if comments are not supported.

3. What did you see instead?

Panic in `lexer.go`:

```
... Panic: runtime error: index out of range (PC=0x402F344)

/usr/local/Cellar/go/1.12.5/libexec/src/runtime/panic.go:522
  in gopanic
/usr/local/Cellar/go/1.12.5/libexec/src/runtime/panic.go:44
  in panicindex
lexer.go:117
  in Scanner.stmtText
```

4. What version of TiDB SQL Parser are you using?

8395edb

**Comment by suzaku** [comment]
[All related bad inputs](https://github.com/pingcap/parser/files/3196921/crashes.zip)

**Comment by kennytm** [comment]
Note that `/*! ... */` isn't a normal comment, but a [conditional comment to hide MySQL-specific code from portable SQL](https://dev.mysql.com/doc/refman/8.0/en/comments.html). That said, it still shouldn't crash.

```
mysql> /*!SET;SET;*/
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
    -> 
```
