### ISSUE TITLE
FLUSH SLOW LOGS parse error

### ISSUE THREAD

**Issue by joyjj0218** [pingcap/parser#340]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB SQL Parser are you using?

**Comment by morgo** [comment]
Thank you for the bug report.

There is a similar bug report in https://github.com/pingcap/parser/issues/140 a little -- perhaps `FLUSH [SLOW|BINARY] LOGS` can be implemented at the same time.
