### ISSUE TITLE
`TableName` rule should not derive to `Identifier '.' '*'`

### ISSUE THREAD

**Issue by kennytm** [pingcap/parser#357]
In fix of #188, the following new rule was introduced:

https://github.com/pingcap/parser/blob/690470b074e1ed6d7ce074ff0ea156787ecee523/parser.y#L4886-L4898

but this affects all uses of TableName and leads to some non-sense syntax being accepted, e.g.

```sql
ANALYZE TABLE a.*;
-- should throw syntax error, but accepted and treated as equivalent to ANALYZE TABLE a;
```

We should create a separate rule for DELETE statement instead, and revert the TableName change.

**Comment by spongedu** [comment]
This issue seems be fixed in #521 . I've added some related test cases in that pr. PTAL. @kennytm
