### ISSUE TITLE
Fix STORAGE syntax

### ISSUE THREAD

**Issue by leoppro** [pingcap/parser#403]
Index Issue: pingcap/tidb#11486

These are bad (incompatible) SQL cases:

```

ALTER TABLE t STORAGE MEMORY STATS_SAMPLE_PAGES 11.11 , LOCK set_var ident
ALTER TABLE t STORAGE MEMORY MAX_ROWS =   11.11 , LOCK ident
ALTER TABLE t STORAGE MEMORY   KEY_BLOCK_SIZE 10
ALTER TABLE t STORAGE MEMORY , LOCK   set_var FILE
ALTER TABLE t STORAGE DISK MAX_ROWS =   123
ALTER TABLE t STORAGE DISK , LOCK =   DEFAULT
ALTER TABLE t STORAGE DISK ,   ALGORITHM set_var XA
ALTER TABLE t STORAGE DISK
ALTER TABLE t PACK_KEYS = DEFAULT STORAGE DISK
ALTER TABLE t STORAGE DISK
ALTER TABLE t ADD ident   NATIONAL CHAR ( 12 ) STORAGE DISK REFERENCES t2 ON UPDATE RESTRICT ON DELETE SET NULL , ADD CHECK ( 1>2 ) NOT   ENFORCED

```

Claim this subtask based on the comments below this issue.

**Comment by leiysky** [comment]
I'll fix it. But where to get specification of `STORAGE`? I didn't find it in manual.

**Comment by leoppro** [comment]
> I'll fix it. But where to get specification of `STORAGE`? I didn't find it in manual.

See:https://github.com/mysql/mysql-server/blob/8.0/sql/sql_yacc.yy#L6094

The description of MySQL docs is different from the implementation.
