### ISSUE TITLE
Fix STATS_SAMPLE_PAGES syntax

### ISSUE THREAD

**Issue by leoppro** [pingcap/parser#404]
Index Issue: pingcap/tidb#11486

These are bad (incompatible) SQL cases:

```
ALTER TABLE t STATS_SAMPLE_PAGES 10
ALTER TABLE t STATS_SAMPLE_PAGES 0x0aaa , LOCK DEFAULT
ALTER TABLE t STATS_SAMPLE_PAGES = 123
ALTER TABLE t STATS_SAMPLE_PAGES = 11.11 AVG_ROW_LENGTH 11
ALTER TABLE t STATS_SAMPLE_PAGES = 10 MIN_ROWS = 12
```

Claim this subtask based on the comments below this issue.

**Comment by leiysky** [comment]
Let me fix it

**Comment by leoppro** [comment]
> Let me fix it

ok thanks

**Comment by leiysky** [comment]
https://github.com/pingcap/parser/blob/2414ee76eeb7bd0b6659fda650c8b98df4945e4c/ast/ddl.go#L1589-L1594
Should I handle it in this way or append a warning in `parser.y`?

**Comment by leoppro** [comment]
no, if we can't restore sql text from ast, we throw a warn in `Restore`
but in this case, the ast include intact sql stmt data, so we don't need to throw a warn.
