### ISSUE TITLE
Fix MATCH syntax 

### ISSUE THREAD

**Issue by leoppro** [pingcap/parser#426]
Index Issue: pingcap/tidb#11486

These are bad (incompatible) SQL cases:

```sql
ALTER TABLE t ADD CONSTRAINT a FOREIGN KEY ( b ( 123 ) DESC , c ) REFERENCES  f MATCH FULL ON DELETE CASCADE ON UPDATE CASCADE
ALTER TABLE t ADD COLUMN ( ident LONGTEXT CHARACTER SET BINARY BINARY  VIRTUAL UNIQUE REFERENCES ident MATCH FULL ON DELETE SET DEFAULT )
ALTER TABLE t ADD COLUMN a DOUBLE ( 4 , 2 ) ZEROFILL REFERENCES b MATCH FULL ON UPDATE SET NULL FIRST
ALTER TABLE t ADD CONSTRAINT FOREIGN KEY ( CHARSET DESC ) REFERENCES b MATCH PARTIAL ON UPDATE RESTRICT ON DELETE SET DEFAULT
```

Claim this subtask based on the comments below this issue.

**Comment by qiukun** [comment]
Let me fix it

**Comment by qiukun** [comment]
The 1st, 2nd and 4th cases seem invalid. The results from Mysql:

1.
ALTER TABLE t ADD CONSTRAINT a FOREIGN KEY ( b ( 123 ) DESC , c ) REFERENCES  f MATCH FULL ON DELETE CASCADE ON UPDATE CASCADE
2 errors were found during analysis.

A new statement was found, but no delimiter between it and the previous one. (near "DESC" at position 55)
Unrecognized alter operation. (near "" at position 0)

2.
ALTER TABLE t ADD COLUMN ( ident LONGTEXT CHARACTER SET BINARY BINARY  VIRTUAL UNIQUE REFERENCES ident MATCH FULL ON DELETE SET DEFAULT )

1 errors were found during analysis.

A new statement was found, but no delimiter between it and the previous one. (near "SET" at position 124)

4.
ALTER TABLE t ADD CONSTRAINT FOREIGN KEY ( CHARSET DESC ) REFERENCES b MATCH PARTIAL ON UPDATE RESTRICT ON DELETE SET DEFAULT

Static analysis:

1 errors were found during analysis.

A new statement was found, but no delimiter between it and the previous one. (near "DESC" at position 51)

**Comment by leoppro** [comment]
```
ALTER TABLE d_n.t_n ADD CONSTRAINT FOREIGN KEY ident ( ident ( 1 ) ) REFERENCES d_n.t_n MATCH FULL ON DELETE SET NULL
ALTER TABLE t_n ADD CONSTRAINT ident FOREIGN KEY ( ident , ident ( 1 ) ) REFERENCES t_n MATCH FULL ON UPDATE SET NULL ON DELETE RESTRICT
ALTER TABLE d_n.t_n ADD FOREIGN KEY ident ( ident , ident ( 1 ) ASC ) REFERENCES t_n MATCH PARTIAL ON DELETE CASCADE REMOVE PARTITIONING
ALTER TABLE d_n.t_n ADD CONSTRAINT FOREIGN KEY ( ident ( 1 ) DESC ) REFERENCES d_n.t_n MATCH PARTIAL ON UPDATE CASCADE , ALGORITHM DEFAULT
ALTER TABLE d_n.t_n ADD CONSTRAINT FOREIGN KEY ( ident ASC ) REFERENCES d_n.t_n MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE
```

**Comment by qiukun** [comment]
How do we generate these? I would like to look at it. Maybe I could make some improvements.

**Comment by leoppro** [comment]
See: https://github.com/leoppro/parser/tree/compatibility_reporter

**Comment by tangenta** [comment]
@qiukun Which version of MySQL did you use? In MySQL 5.7.26, all of the statements above can be parsed successfully.

**Comment by qiukun** [comment]
@tangenta I just pick a free mysql service and use its phpMyAdmin. Here is what `SHOW VARIABLES LIKE "%version%"` shows:

innodb_version | 5.7.18
-- | --
protocol_version | 10
slave_type_conversions |  
tls_version | TLSv1,TLSv1.1
version | 5.7.18-txsql-log
version_comment | 20181030
version_compile_machine | x86_64
version_compile_os | Linux

**Comment by leoppro** [comment]
it's not a important problem in fact
