### ISSUE TITLE
Should we need to support `.` in System Variables?

### ISSUE THREAD

**Issue by wjhuang2016** [pingcap/parser#428]
According to https://dev.mysql.com/doc/refman/8.0/en/using-system-variables.html

> System variables implemented by a server component are exposed when the component is installed and have names that begin with a component-specific prefix. For example, the log_filter_dragnet error log filter component implements a system variable named log_error_filter_rules, the full name of which is dragnet.log_error_filter_rules. To refer to this variable, use the full name.

The problem I met is in [#9812](https://github.com/pingcap/tidb/pull/9812) . Presently, TiDB doesn't support `.` in a identifier. After MySQL 8.0, validate_password became a component and its variables uses a `.` instead of `_` to sepearate  component name.
So I wonder should we need to support `.` in system variables or just using `_`?

**Comment by tiancaiamao** [comment]
Could you do this in MySQL8  `set @@SESSION.validate_password.policy = xxx`? @wjhuang2016

**Comment by wjhuang2016** [comment]
> Could you do this in MySQL8 `set @@SESSION.validate_password.policy = xxx`? @wjhuang2016

No, I couldn't.
```
mysql> set @@SESSION.validate_password.policy = low;
ERROR 1229 (HY000): Variable 'validate_password.policy' is a GLOBAL variable and should be set with SET GLOBAL
mysql> set @@GLOBAL.validate_password.policy = low;
Query OK, 0 rows affected (0.00 sec)
```

**Comment by tiancaiamao** [comment]
Just now I try it and doubt that "TiDB doesn't support . in a identifier."

git diff:
```
diff --git a/sessionctx/variable/sysvar.go b/sessionctx/variable/sysvar.go
index f42c04bf3..fbd5aaba8 100644
--- a/sessionctx/variable/sysvar.go
+++ b/sessionctx/variable/sysvar.go
@@ -227,6 +227,7 @@ var defaultSysVars = []*SysVar{
        {ScopeNone, "ssl_key", ""},
        {ScopeNone, "ssl_cipher", ""},
        {ScopeNone, "tls_version", "TLSv1,TLSv1.1,TLSv1.2"},
+       {ScopeGlobal | ScopeSession, "xx.xx", "666"},
        {ScopeNone, "system_time_zone", "CST"},
        {ScopeGlobal, InnodbPrintAllDeadlocks, "0"},
        {ScopeNone, "innodb_autoinc_lock_mode", "1"},
```

and use the modified tidb:

```
mysql> select @@session.xx.xx;
+-----------------+
| @@session.xx.xx |
+-----------------+
| 666             |
+-----------------+
1 row in set (0.01 sec)

mysql> select @@global.xx.xx;
+----------------+
| @@global.xx.xx |
+----------------+
| 666            |
+----------------+
1 row in set (0.00 sec)
```

@wjhuang2016

**Comment by wjhuang2016** [comment]
@tiancaiamao 
Could you do this `set global xx.xx=666;`?

**Comment by tiancaiamao** [comment]
I see! @wjhuang2016

**Comment by tiancaiamao** [comment]
I've filed a PR to address it. @wjhuang2016
