### ISSUE TITLE
some test case failed

### ISSUE THREAD

**Issue by 464319127** [pingcap/parser#43]
```go
func main(){

    sql := "select * from wn where id = 2"

    pa := parser.New()

    //set charsetInfo and collation
    charsetInfo, collation := "utf8", "utf8_general_ci" 

    pa.SetSQLMode(mysql.ModeNone)

    stmtNodes, err := pa.Parse( sql, charsetInfo, collation)

    fmt.Println(stmtNodes[0], err)
}
```

It works when I use sql="select * from wn"

But it failed when I use sql="select * from wn where id = 2"

The golang version is 1.11.1 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5e3ef8]

goroutine 1 [running]:
github.com/pingcap/parser.yyParse(0x715e60, 0xc000154048, 0xc000154000, 0xc00010bf68)
	/root/wn/go/pkg/mod/github.com/pingcap/parser@v0.0.0-20181119030059-e8ee63ef2cb2/parser.go:8654 +0x16ac8
github.com/pingcap/parser.(*Parser).Parse(0xc000154000, 0x7fffc6f056eb, 0x1b, 0x6b7519, 0x4, 0x6bd81d, 0xf, 0x0, 0x0, 0xc00010bf10, ...)
	/root/wn/go/pkg/mod/github.com/pingcap/parser@v0.0.0-20181119030059-e8ee63ef2cb2/yy_parser.go:101 +0x15f
main.main()
	/root/wn/go/test2/hello.go:26 +0x2a9
```

**Comment by shenli** [comment]
@tiancaiamao @lysu PTAL

**Comment by 464319127** [comment]
@lysu thanks a lot. It works now.

**Comment by 464319127** [comment]
`import _ "github.com/pingcap/tidb/types/parser_driver"`
when I add the import in head, the go mod default require the tidb@v2.0.9+incompatible. But there is no  "tidb/types/parser_driver" in tidb@v2.0.9+incompatible.
So I use go get github.com/pingcap/tidb@master to get it. Then I modify the go.mod 
`
require (
    github.com/pingcap/parser v0.0.0-20181120072820-10951bcfca73
    github.com/pingcap/tidb v0.0.0-20181120082053-012cb6da9443
)
`

**Comment by winjeg** [comment]
这个parser拆的也太不清真了吧， 要使用还要 `go get tidb` 驱动为啥不放在parser里

**Comment by rarpainting** [comment]
@464319127 
For dependencies, see the top description of `value_expr.go`

**Comment by rarpainting** [comment]
@winjeg 
For dependencies, see the description of value_expr.go

**Comment by winjeg** [comment]
Now it's not working according to the offical document, I was lead back here by the error print in my co nsole.

**Comment by tiancaiamao** [comment]
Try this command:

```
go get -u github.com/pingcap/tidb@master
```

@winjeg

**Comment by bugcai** [comment]
> ```
> go get -u github.com/pingcap/tidb@master
> ```

The command cannot run under Go 1.13.
"go: cannot use path@version syntax in GOPATH mode"

**Comment by funlake** [comment]
> Try this command:
> 
> ```
> go get -u github.com/pingcap/tidb@master
> ```
> 
> @winjeg

Didn't works,got error
go get: error loading module requirements

**Comment by Xeoncross** [comment]
> > ```
> > go get -u github.com/pingcap/tidb@master
> > ```
> 
> why cannot " go get github.com/pingcap/tidb@v3.0.5"?

Good question. `master` currently points at `tidb@v1.1.0-beta.0.20200417160137-a0c7407846fb` which claims to be from April 4th, but isn't a release/tag: https://github.com/pingcap/tidb/tags

**Comment by didip** [comment]
I am guessing that `parser_driver` is deleted in tidb?

```
go: finding module for package github.com/pingcap/tidb/types/parser_driver
main.go:7:2: module github.com/pingcap/tidb@latest found (v2.0.11+incompatible), but does not contain package github.com/pingcap/tidb/types/parser_driver
```

**Comment by lwfofgit** [comment]
tidb最新版本没有parser_driver包，应该依赖版本啊

**Comment by zhangysh1995** [comment]
I solved a first error with #812, and I got this error again:

````
go: finding module for package github.com/pingcap/tidb/types/parser_driver
main.go:7:2: module github.com/pingcap/tidb@latest found (v2.0.11+incompatible), but does not contain package github.com/pingcap/tidb/types/parser_driver

Compilation finished with exit code 1
````

My import:
````
import (
	"fmt"
	"github.com/pingcap/parser"
	"github.com/pingcap/parser/ast"
	_ "github.com/pingcap/tidb/types/parser_driver"
)
````

**Comment by zhangysh1995** [comment]
For anyone who has this issue, please see my comments [here](https://github.com/pingcap/parser/issues/812#issuecomment-685674341).

**Comment by TerryLiu** [comment]
import _ "github.com/pingcap/parser/test_driver"

**Comment by dobet** [comment]
no bady update quickstart? and reslove this problem?

**Comment by twz915** [comment]
```
import (
	_ "github.com/pingcap/tidb/pkg/parser/test_driver"
)
```
