### ISSUE TITLE
Fix PARTITION LOCAL syntax

### ISSUE THREAD

**Issue by leoppro** [pingcap/parser#443]
Index Issue: pingcap/tidb#11486

These are bad (incompatible) SQL cases:

```sql
ALTER TABLE d_n.t_n ADD PARTITION LOCAL
ALTER TABLE d_n.t_n COALESCE PARTITION LOCAL 11
ALTER TABLE t_n ADD PARTITION LOCAL PARTITIONS 10
```

Claim this subtask based on the comments below this issue.

**Comment by spongedu** [comment]
@leoppro  `LOCAL` is alias to `NO_WRITE_TO_BINLOG`,  so this issue is duplicate to #445
