### ISSUE TITLE
Fix DROP INDEX ... LOCK syntax

### ISSUE THREAD

**Issue by leoppro** [pingcap/parser#459]
Index Issue: pingcap/tidb#11486

These are bad (incompatible) SQL cases:

```sql
DROP INDEX ident ON t_n LOCK = DEFAULT 
DROP INDEX ident ON t_n LOCK DEFAULT 
DROP INDEX ident ON t_n LOCK = lock_type 
DROP INDEX ident ON t_n LOCK lock_type 
```

Claim this subtask based on the comments below this issue.

**Comment by zhenghaoz** [comment]
Oh! `LOCK` & `ALGORITHM`. Let me fix it :D
