### ISSUE TITLE
Fix ALTER TABLE ... RENAME syntax

### ISSUE THREAD

**Issue by leoppro** [pingcap/parser#461]
Index Issue: pingcap/tidb#11486

These are bad (incompatible) SQL cases:

```sql
ALTER TABLE t_n RENAME = t_n
ALTER TABLE t_n RENAME TO t_n
ALTER TABLE t_n RENAME AS t_n
```

Claim this subtask based on the comments below this issue.

**Comment by tangwz** [comment]
Let me fix it
