### ISSUE TITLE
Fix ALTER TABLE ... ALTER INDEX syntax

### ISSUE THREAD

**Issue by leoppro** [pingcap/parser#463]
Index Issue: pingcap/tidb#11486

These are bad (incompatible) SQL cases:

```sql
ALTER TABLE t_n ALTER INDEX ident INVISIBLE 
ALTER TABLE t_n ALTER INDEX ident VISIBLE 
```

Claim this subtask based on the comments below this issue.

**Comment by tangwz** [comment]
Let me fix it
