### ISSUE TITLE
Fix CREATE INDEX .. ALGORITHM syntax

### ISSUE THREAD

**Issue by leoppro** [pingcap/parser#477]
Index Issue: pingcap/tidb#11486

These are bad (incompatible) SQL cases:

```sql
CREATE UNIQUE INDEX ident ON d_n.t_n ( ident ) ALGORITHM = DEFAULT
```

Claim this subtask based on the comments below this issue.

**Comment by zhenghaoz** [comment]
It seems to have been fixed in #454
