### ISSUE TITLE
Fix CREATE INDEX .. VISIBLE/INVISIBLE syntax

### ISSUE THREAD

**Issue by leoppro** [pingcap/parser#478]
Index Issue: pingcap/tidb#11486

These are bad (incompatible) SQL cases:

```sql
CREATE INDEX ident ON t_n ( ident ) VISIBLE 
CREATE INDEX ident ON t_n ( ident ) INVISIBLE 
```

Claim this subtask based on the comments below this issue.

**Comment by zhenghaoz** [comment]
Let me fix it ^_^
