### ISSUE TITLE
Fix ORDER BY syntax

### ISSUE THREAD

**Issue by leoppro** [pingcap/parser#499]
Index Issue: pingcap/tidb#11486

These are bad (incompatible) SQL cases:

```sql
ALTER TABLE t_n ORDER BY ident
```

Claim this subtask based on the comments below this issue.

**Comment by zuoRambo** [comment]
Let me fix it

**Comment by zuoRambo** [comment]
#### I have some confusions.
1. In [Mysql 8.0 Alter Table Doc](https://dev.mysql.com/doc/refman/8.0/en/alter-table.html): Alter Table Syntax is `| ORDER BY col_name [, col_name] ...`, which means it just need `col_name` after `order by`.
![image](https://user-images.githubusercontent.com/4715122/63792862-07072500-c931-11e9-95bd-8e748a6997fc.png)


2. But in [Mysql yacc file `Order by statement in ALTER TABLE`](https://github.com/mysql/mysql-server/blob/8.0/sql/sql_yacc.yy#L11535) . It has `opt_ordering_direction(ASC|DESC)`.
![image](https://user-images.githubusercontent.com/4715122/63792826-f35bbe80-c930-11e9-9047-9535373da71b.png)

So i think there must something wrong.
![image](https://user-images.githubusercontent.com/4715122/63792959-3cac0e00-c931-11e9-9cfb-422c1bf4881c.png)

**Comment by kennytm** [comment]
The doc is not always complete. Let's also support the ordering direction.

```sql
ALTER TABLE t ORDER BY a ASC, b DESC, c;
```
