### ISSUE TITLE
Fix DISCARD/IMPORT TABLESPACE syntax

### ISSUE THREAD

**Issue by leoppro** [pingcap/parser#501]
Index Issue: pingcap/tidb#11486

These are bad (incompatible) SQL cases:

```sql
ALTER TABLE d_n.t_n IMPORT TABLESPACE 
ALTER TABLE d_n.t_n DISCARD TABLESPACE
```

Claim this subtask based on the comments below this issue.

**Comment by fzhedu** [comment]
Let me fix it
