### ISSUE TITLE
Fix LOCK clause error message

### ISSUE THREAD

**Issue by tangenta** [pingcap/parser#508]
Index Issue: pingcap/tidb#11486

These are bad (incompatible) SQL cases:

```sql
alter table t lock = first
alter table t lock = start
alter table t lock = commit
alter table t lock = binlog
```

The body `"LOCK" EqOpt identifier` in `LockClause` should be used when the `identifier` is an unreserved keyword, and report 
```
Error 1801: Unknown LOCK type 'first'
```
in the first example. However, TiDB parser reports: 
```
Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 26 near "first"
```

Claim this subtask based on the comments below this issue.

**Comment by lauhg** [comment]
Let me fix it.
