### ISSUE TITLE
Curious: why use `go.mod1` instead of `go.mod`?

### ISSUE THREAD

**Issue by ichn-hu** [pingcap/parser#532]
## Question

Out of curious, why the code use `go.mod1` (and also `go.sum1`) instead of the standard `go.mod` as the filename, and whenever we test or build the project we rename these files into the default `go.mod`? Is it because of capatibility issues or any other reasons that make such practice better?

BTW, if use different name from the default `go.mod` how can you not break the linter during development? In my case I have to duplicate the two files into the default filename before development, but it will be broken once I `make test`, and I have to recopy them again to restart the development.

**Comment by wty4427300** [comment]
because tidb and parser are interdependent
