### ISSUE TITLE
Remove CONSTRAINT syntax for KEY | INDEX | FULLTEXT

### ISSUE THREAD

**Issue by tangenta** [pingcap/parser#535]
Index Issue: pingcap/tidb#11486

These SQL cases do not work in MySQL, but they work in TiDB parser:

```sql
create table t (a int, constraint c key idx (a))
create table t (a int, constraint c index idx (a))
create table t (a int, constraint c key idx using hash (a))
create table t (a int, constraint c index idx using rtree (a))
create table t (a int, constraint c fulltext index (a))
```

`ConstraintKeywordOpt` is not applicable in `KEY`, `INDEX`, or `FULLTEXT` according to the grammar of MySQL 8.0.

Claim this subtask based on the comments below this issue.

**Comment by wty4427300** [comment]
Let me fix it
