### ISSUE TITLE
Fix TiDB behavior: union

### ISSUE THREAD

**Issue by tangenta** [pingcap/parser#602]
Index issue: #598 

### SQL example
```sql
CREATE TABLE x (a INT) ENGINE = MyISAM;
CREATE TABLE y (a INT) ENGINE = MyISAM;
INSERT INTO x VALUES (1);
INSERT INTO y VALUES (2);
CREATE TABLE z (a INT) ENGINE = MERGE UNION = (x, y);
```

### Current implementation
Both `TableOptionUnion` and
`TableOptionInsertMethod` are ignored by TiDB.

### Expected implementation
Report an error.

**Comment by bb7133** [comment]
I will close this issue because of tidb/#17995
