### ISSUE TITLE
Fix TiDB behavior: with validation

### ISSUE THREAD

**Issue by tangenta** [pingcap/parser#606]
Index issue: #598 

### SQL example
```sql
ALTER TABLE t WITH VALIDATION;
```

### Current implementation
`AlterTableWithValidation` is ignored by TiDB.

### Expected implementation
Throw a warning only when the table is with validation.

**Comment by yuanjize** [comment]
Should these problem about incompatible statements be fixed in repo parser or repo tidb?

**Comment by tangenta** [comment]
@yuanjize We need to update the code in TiDB repo.

**Comment by tangenta** [comment]
@yuanjize If you have any questions, feel free to ask here or contact me on slack :).
> Slack: channel #sig-parser in the [tidbcommunity](https://pingcap.com/tidbslack) slack workspace.

**Comment by cncal** [comment]
@tangenta , I'm working on this issue as a new contributor. A warning is threw when I execute `ALTER TABLE t WITH VALIDATION;` and the warning is as follows:

> 1064 You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 30 near ""The WITH/WITHOUT VALIDATION clause is parsed but ignored by all storage engines.

Has this issue been solved already?

**Comment by tangenta** [comment]
@cncal This issue has not been fixed yet. Your contribution is welcomed :)

**Comment by cncal** [comment]
I think the warning has been generated by [parser](https://github.com/pingcap/parser/blob/68d423641be5babd4d209c2ce711400aac7eb3fc/parser.y#L1797), should I remove the code that generates the warning in parser and throw the warning in tidb?

**Comment by tangenta** [comment]
Yes, you can remove the warning in parser.
