### ISSUE TITLE
Fix TiDB behavior: rename column

### ISSUE THREAD

**Issue by tangenta** [pingcap/parser#607]
Index issue: #598 

### SQL example
```sql
ALTER TABLE t RENAME COLUMN a TO b;
```

### Current implementation
`AlterTableRenameColumn` is ignored by TiDB.

### Expected implementation
Report an error like `ErrUnsupportedRenameColumn`.

**Comment by gauss1314** [comment]
Hi, I find this issue is fix by [tidb#14281](https://github.com/pingcap/tidb/pull/14281).
So this can be closed.
