### ISSUE TITLE
BUG: parsing UseStmt.DBName is not in line with expectations

### ISSUE THREAD

**Issue by leoppro** [pingcap/parser#61]
In TiDB Parser, version: master in repo
```
stmt, _ := parser.ParseOneStmt("use abc`def", "", "")
fmt.Printf("%#v",stmt)
```
```
&ast.UseStmt{stmtNode:ast.stmtNode{node:ast.node{text:"use abc`def"}}, DBName:"abc"}
```
In MariaDB(MySQL Untested), version: 10.3.10-MariaDB
```
MariaDB [(none)]> use na`me
Database changed
MariaDB [na`me]> 
```

Maybe we don't support this way, but we should't get a part of name.

**Comment by kennytm** [comment]
The ``use na`me;`` working looks like a bug in MariaDB.

```sql
mysql> use foo`bar;
    `> 
```

```console
$ mysql -u root -e 'use foo`bar;'
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '`bar' at line 1
```

**Comment by winkyao** [comment]
@leoppro what is the behavior of mysql?

**Comment by leoppro** [comment]
even if mysql don't support it, i think out parser should return an error instead of a silent error

**Comment by winkyao** [comment]
It depends on the sqlmode, if the sql mode is ANSI_QUOTES, TiDB will treats the " as the quote not `, so why we need to return error?

**Comment by leoppro** [comment]
ok, i understood.
