### ISSUE TITLE
Make TiDB accept 'AND NO CHAIN NO RELEASE' in SQL syntax

### ISSUE THREAD

**Issue by YouhuaLi** [pingcap/parser#649]
## Feature Request

**Is your feature request related to a problem? Please describe:**

When I test my current application with TiDB, I got a lot of errors as:

```'You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 12 near \"AND NO CHAIN NO RELEASE\" ')]"```

**Describe the feature you'd like:**

Make TiDB accept ['AND NO CHAIN NO RELEASE'](https://dev.mysql.com/doc/refman/8.0/en/commit.html) as valid SQL syntax, by even do nothing and ignore that. 

**Describe alternatives you've considered:**

I can change my existing software code to remove those codes, but that will be a lot of efforts and break online migraiton process. 

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by shenli** [comment]
@YouhuaLi Could you show use the whole statement? Thanks!

**Comment by shenli** [comment]
https://dev.mysql.com/doc/refman/8.0/en/commit.html

**Comment by YouhuaLi** [comment]
they are just:

```
COMMIT AND NO CHAIN NO RELEASE
ROLLBACK AND NO CHAIN NO RELEASE
```

**Comment by dasinlsb** [comment]
let me try it :)
