### ISSUE TITLE
may remove tokenStr in isTokenIdentifier 

### ISSUE THREAD

**Issue by siddontang** [pingcap/parser#653]
## Question

https://github.com/pingcap/parser/blob/master/misc.go#L756

```
	checkBtFuncToken, tokenStr := false, string(data)
	if s.r.peek() == '(' {
		checkBtFuncToken = true
	} else if s.sqlMode.HasIgnoreSpaceMode() {
		s.skipWhitespace()
		if s.r.peek() == '(' {
			checkBtFuncToken = true
		}
	}
	if checkBtFuncToken {
		if tok := btFuncTokenMap[tokenStr]; tok != 0 {
			return tok
		}
	}
	tok, ok := tokenMap[string(data)]
	if !ok && s.supportWindowFunc {
		tok = windowFuncTokenMap[string(data)]
	}
	return tok
```
Refer to https://github.com/golang/go/wiki/CompilerOptimizations#map-lookup-by-byte, maybe we can use `string(data)` all the time and remove tokenStr.

**Comment by coocood** [comment]
According to https://github.com/golang/go/wiki/CompilerOptimizations#map-lookup-by-byte
We should always use `string(data)` to lookup in map.

**Comment by siddontang** [comment]
so here we need to remove tokenStr.
