### ISSUE TITLE
parser : TiDB Sequence shouldn't used as a reserved keyword.

### ISSUE THREAD

**Issue by AilinKid** [pingcap/parser#672]
#### Please answer these questions before submitting your issue. Thanks!

TiDB SEQUENCE should be used as a reserved keyword.
It should be compatible with the [MySQL keyword standard](https://dev.mysql.com/doc/refman/8.0/en/keywords.html).

#### What version of TiDB SQL Parser are you using?

the latest master of parser.

**Comment by kennytm** [comment]
Fixed in #673.
