### ISSUE TITLE
remove dependency on TiDB

### ISSUE THREAD

**Issue by tangenta** [pingcap/parser#677]
Currently, the tests in parser are depended on the packages in TiDB like `testleak`, `types` and `parser_driver`. On the other hand, TiDB also depends on the parser. This circular dependency has caused a lot of inconveniences, including
- the code in an old-version TiDB must be imported before using the parser
- `go.mod` and `go.sum` must be named as `go.mod1` and `go.sum1`

In order to solve circular dependency, we can copy the package `testleak` from TiDB to parser and mock a `parser_driver` for tests in parser.

**Comment by kennytm** [comment]
Can we now properly name those files as go.mod and go.sum?
