### ISSUE TITLE
Support the `SELECT ... INTO OUTFILE` syntax

### ISSUE THREAD

**Issue by qw4990** [pingcap/parser#722]
## Feature Request

**Is your feature request related to a problem? Please describe:**

No.

**Describe the feature you'd like:**

From MySQL documentation [13.2.10.1 SELECT ... INTO OUTFILE Syntax](https://dev.mysql.com/doc/refman/8.0/en/select-into.html):
> SELECT ... INTO OUTFILE writes the selected rows to a file. Column and line terminators can be specified to produce a specific output format.

It helps us to store the query result in a CSV form.

Here is a [discarded PR](https://github.com/pingcap/parser/pull/645) that may as a reference for you.

NOTE: do not support `INTO DUMPFILE` and `INTO VARIABLES`, supporting the `INTO OUTFILE` syntax is enough in this issue.

**Comment by kennytm** [comment]
> NOTE: do not support INTO DUMPFILE and INTO VARIABLES, supporting the INTO OUTFILE syntax is enough in this issue.

Do you mean supporting INTO DUMPFILE and VARIABLES is fine but not necessary?

**Comment by qw4990** [comment]
> > NOTE: do not support INTO DUMPFILE and INTO VARIABLES, supporting the INTO OUTFILE syntax is enough in this issue.
> 
> Do you mean supporting INTO DUMPFILE and VARIABLES is fine but not necessary?

Emm yes.
