### ISSUE TITLE
use this package , but get all github.com/pingcap/tidb

### ISSUE THREAD

**Issue by chyroc** [pingcap/parser#788]
我使用 quickstart 的例子，但是下载了整个 tidb

这对于我这个只想使用 parser 的人来说，太大了

![image](https://user-images.githubusercontent.com/15604894/77666770-53483f80-6fbc-11ea-8577-a958c8dfd71b.png)

**Comment by kennytm** [comment]
Hi.

The quick start relies on TiDB to provide the "[parser driver](https://github.com/pingcap/parser/blob/master/docs/quickstart.md#import-driver)", referring to concrete implementation of these 5 functions:

* [`ast.NewDecimal`, `ast.NewHexLiteral`, `ast.NewBitLiteral`](https://github.com/pingcap/parser/blob/68d423641be5babd4d209c2ce711400aac7eb3fc/ast/misc.go#L2608-L2615)
* [`ast.NewValueExpr`, `ast.NewParamMarkerExpr`](https://github.com/pingcap/parser/blob/68d423641be5babd4d209c2ce711400aac7eb3fc/ast/expressions.go#L67-L71)

You could avoid the TiDB dependency by manually assigning them, but doing so would no longer be a "quick" start, so... 🤷‍

**Comment by chyroc** [comment]
so，parser should be a single package

**Comment by at15** [comment]
Maybe we can use the test_driver  package in quick start?

**Comment by liumingc** [comment]
> Maybe we can use the test_driver package in quick start?

Need to remove the `+build !codes` flag in test_driver, and removed the charset and collate params in newValueExpr.
