### ISSUE TITLE
Support using dash('-') in config item names

### ISSUE THREAD

**Issue by qw4990** [pingcap/parser#820]
## Feature Request

**Is your feature request related to a problem? Please describe:**

After this issue(https://github.com/pingcap/parser/issues/768), the parser supports `set config name=value` syntax, but the name doesn't support using `-`.
We should support it since there are some config items like `label-property.reject-leader`, `auto-compaction` which use `-` in their names.

**Describe the feature you'd like:**

Support using dash(`-`) in config item names, for examples:
1. `set config pd auto-compation=true`
2. `set config pd property.reject-leader.key='zone'`

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by kennytm** [comment]
```sql
set config pd `label-property`.`reject-leader` = 'zone';
```

should work?
