### ISSUE TITLE
Introduce a new privilege for the `set config` statement

### ISSUE THREAD

**Issue by qw4990** [pingcap/parser#826]
## Feature Request

**Describe the feature you'd like:**

After https://github.com/pingcap/parser/issues/768, we can use `set config` on TiDB to update configs of TiKV/PD.
Now the privilege of this statement is `PrivSuper`, which is not appropriate.
We should introduce a new privilege for it.

**Describe alternatives you've considered:**

No

**Comment by kennytm** [comment]
if not super privilege, would that user be allowed to change privileged settings like:?

```sql
set config security.skip-grant-table = true;
```

**Comment by qw4990** [comment]
> if not super privilege, would that user be allowed to change privileged settings like:?
> 
> ```sql
> set config security.skip-grant-table = true;
> ```

@tiancaiamao  Could you please give us some suggestions about this case...

**Comment by qw4990** [comment]
> if not super privilege, would that user be allowed to change privileged settings like:?
> 
> ```sql
> set config security.skip-grant-table = true;
> ```

After discussing with @tiancaiamao , we decide to handle security config items especially, which require both `SuperPriv` and `SetConfPriv` when modifying.

**Comment by tiancaiamao** [comment]
Allow the modification of  `skip-grant-table` dynamically  would because a vulnerability.
Skip grant table is a special config which is used to disaster recover from misoperation, maybe we do not have the necessity to dynamic change this config.
