### ISSUE TITLE
SQL syntax parsing exception when the field name in the SQL statement is `error`

### ISSUE THREAD

**Issue by bloodsucker1** [pingcap/parser#846]
## Bug Report
SQL syntax parsing exception when the field name in the SQL statement is `error`,

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
func TestExample(t *testing.T) {
	p := parser.New()
	stmtNodes, _, err := p.Parse("select message_id,error,update_time from test", "", "")
	fmt.Println(stmtNodes[0], err)
}
```

2. What did you expect to see?
Get sql syntax tree

3. What did you see instead?
Syntax parsing exception
```
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0
goroutine 36 [running]:
```
4. What version of TiDB SQL Parser are you using?
v0.0.0-20200218113622-517beb2e39c2

**Comment by kennytm** [comment]
Thanks for the bug report. `ERROR` is not a reserved word in MySQL 8.0 (there is no `(R)` in https://dev.mysql.com/doc/refman/8.0/en/keywords.html), but was classified as one in the parser.

The other keywords with the same problem:

* chain
* error
* general
* nvarchar
* pack_keys
* parser
