### ISSUE TITLE
How do I get the position of an AST node?

### ISSUE THREAD

**Issue by kyleconroy** [pingcap/parser#910]
For [sqlc](https://github.com/kyleconroy/sqlc), I need to know the position of individual AST nodes in the original source text. The PostgreSQL parser I'm using ([pg_query_go](https://github.com/lfittl/pg_query_go/)) attaches a `Location` to many of the AST nodes.

This package has a `Pos` struct, but I don't see a way to get a Pos for a given AST node. Am I missing something?

**Comment by zimulala** [comment]
PTAL @tangenta

**Comment by tangenta** [comment]
The struct `Pos` is only used in the lexer. For now, I think it is not possible to get the source text location of an AST node.

**Comment by kyleconroy** [comment]
How difficult would this be to add? Do you think it would be a good first issue to work on?

**Comment by tangenta** [comment]
You need to pass this information from the lexer to AST nodes. The following changes are required (may not be complete):

- Add one more method (like `Position()`) to the interface `yyLexer`.
- Implement `yyLexer` for `Scanner`.
- Pass the position info to **every** AST node when they are initialized. There are two ways to achieve this:
    - add them manually (this can be tedious), or
    - add them automatically through pattern matching when generating `parser.go`

Anyway, you can have a try if you are familiar with yacc.
