### ISSUE TITLE
go get faile

### ISSUE THREAD

**Issue by abao2016** [pingcap/parser#934]
go get -v github.com/pingcap/parser@v4.0.0-rc.1
go: finding github.com/pingcap/parser v4.0.0-rc.1
go get github.com/pingcap/parser@v4.0.0-rc.1: github.com/pingcap/parser@v4.0.0-rc.1: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v4

**Comment by abao2016** [comment]
main.go:6:2: module github.com/pingcap/parser@latest found (v3.1.2+incompatible), but does not contain package github.com/pingcap/parser/test_driver

**Comment by abao2016** [comment]
panic: no parser driver (forgotten import?) https://github.com/pingcap/parser/issues/43

goroutine 1 [running]:
github.com/pingcap/parser.New(...)
        /Users/bytedance/go/pkg/mod/github.com/pingcap/parser@v3.1.2+incompatible/yy_parser.go:112
main.parse(0x13e561e, 0x12, 0xc000123f20, 0x103a7da, 0x1695480)
        /Users/bytedance/Documents/bytedance/go/colx/main.go:10 +0x1b6
main.main()
        /Users/bytedance/Documents/bytedance/go/colx/main.go:21 +0x3a
exit status 2

**Comment by zimulala** [comment]
PTAL @tiancaiamao

**Comment by cncal** [comment]
@abao2016 you may take [this issue](https://github.com/golang/go/issues/35732) as a reference.

**Comment by tangenta** [comment]
Duplicate with https://github.com/pingcap/parser/issues/812.
