### ISSUE TITLE
run faild

### ISSUE THREAD

**Issue by abao2016** [pingcap/parser#936]
package main
import (
	"fmt"
	"github.com/pingcap/parser"
	"github.com/pingcap/parser/ast"
	_ "github.com/pingcap/tidb/types/parser_driver"

	//
	//"github.com/pingcap/tidb/types/parser_driver"
	//_ "github.com/pingcap/parser/test_driver"
)

func parse(sql string) (*ast.StmtNode, error) {
	p := parser.New()

	stmtNodes, _, err := p.Parse(sql, "", "")
	if err != nil {
		return nil, err
	}

	return &stmtNodes[0], nil
}

func main() {
	astNode, err := parse("SELECT a, b FROM t")
	if err != nil {
		fmt.Printf("parse error: %v\n", err.Error())
		return
	}
	fmt.Printf("%v\n", *astNode)
	fmt.Println("sucesss")
}

github.com/pingcap/tidb/types/parser_driver
../../../../go/pkg/mod/github.com/pingcap/tidb@v0.0.0-20181120082053-012cb6da9443/types/parser_driver/value_expr.go:59:2: cannot use &ParamMarkerExpr literal (type *ParamMarkerExpr) as type ast.ParamMarkerExpr in assignment:
        *ParamMarkerExpr does not implement ast.ParamMarkerExpr (missing Restore method)
../../../../go/pkg/mod/github.com/pingcap/tidb@v0.0.0-20181120082053-012cb6da9443/types/parser_driver/value_expr.go:60:2: cannot use &ValueExpr literal (type *ValueExpr) as type ast.ValueExpr in assignment:
        *ValueExpr does not implement ast.ValueExpr (missing Restore method)
../../../../go/pkg/mod/github.com/pingcap/tidb@v0.0.0-20181120082053-012cb6da9443/types/parser_driver/value_expr.go:116:3: cannot use ve (type *ValueExpr) as type ast.ValueExpr in return argument:
        *ValueExpr does not implement ast.ValueExpr (missing Restore method)
../../../../go/pkg/mod/github.com/pingcap/tidb@v0.0.0-20181120082053-012cb6da9443/types/parser_driver/value_expr.go:122:2: cannot use ve (type *ValueExpr) as type ast.ValueExpr in return argument:
        *ValueExpr does not implement ast.ValueExpr (missing Restore method)
../../../../go/pkg/mod/github.com/pingcap/tidb@v0.0.0-20181120082053-012cb6da9443/types/parser_driver/value_expr.go:137:34: cannot use n (type *ValueExpr) as type ast.Node in argument to v.Enter:
        *ValueExpr does not implement ast.Node (missing Restore method)
../../../../go/pkg/mod/github.com/pingcap/tidb@v0.0.0-20181120082053-012cb6da9443/types/parser_driver/value_expr.go:141:13: impossible type assertion:
        *ValueExpr does not implement ast.Node (missing Restore method)
../../../../go/pkg/mod/github.com/pingcap/tidb@v0.0.0-20181120082053-012cb6da9443/types/parser_driver/value_expr.go:142:16: cannot use n (type *ValueExpr) as

**Comment by zimulala** [comment]
PTAL @tangenta @kennytm

**Comment by tangenta** [comment]
@abao2016 The git hash of TiDB dependency seems to be outdated. 

Please follow the steps in [quickstart](https://github.com/pingcap/parser/blob/master/docs/quickstart.md#import-dependencies) to import the dependency. If it still does not work, see https://github.com/pingcap/parser/issues/812 for a temporary solution.

**Comment by tangenta** [comment]
Duplicate with https://github.com/pingcap/parser/issues/812.
