### ISSUE TITLE
Incompatible for select ... for share statements.

### ISSUE THREAD

**Issue by cncal** [pingcap/parser#945]
## Bug Report

1. What did you do?

```sql
mysql> CREATE TABLE t (i INT, PRIMARY KEY (i)) ENGINE = InnoDB;
mysql> INSERT INTO t (i) VALUES(1),(2),(3);
mysql> SELECT * FROM test.t FOR SHARE;
```

2. What did you expect to see?

```
+---+
| i |
+---+
| 1 |
+---+
| 2 |
+---+
| 3 |
+---+
```
3. What did you see instead?

```
Error Code: 1064. You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 30 near "SHARE" 
```

4. What version of TiDB SQL Parser are you using?

    `v0.0.0-20200623082809-b74301ac298b`

In MySQL 8.0, `SELECT ... LOCK IN SHARE` has been replaced by `SELECT ... FOR SHARE`.

**Comment by bb7133** [comment]
Hi @cncal , thanks for reporting it. IMOH this is a simple compatibility issue and I've marked it 'for new contributors'.
