### ISSUE TITLE
Support parsing window function in MySQL.

### ISSUE THREAD

**Issue by brightcoder01** [pingcap/parser#959]
## Feature Request

**Is your feature request related to a problem? Please describe:**
The window function is common used in MySQL. It would be very useful that TiDB parser can support the statement of the following type.
```SQL
SELECT LAG(high, 1) OVER (ORDER BY date) AS high_lag_1 FROM stocks.apple_daily;
```

**Describe the feature you'd like:**
Support the window function like `SELECT LAG(high, 1) OVER (ORDER BY date) AS high_lag_1 FROM stocks.apple_daily;`

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by kennytm** [comment]
Hello. What is the parser version you are using? TiDB already supports window function since #37.

**Comment by brightcoder01** [comment]
> Hello. What is the parser version you are using? TiDB already supports window function since #37.

I just copy the code from the tutorial to `main.go` and replace the sample SQL:

```go
package main

import (
	"fmt"

	"github.com/pingcap/parser"
	"github.com/pingcap/parser/ast"
	_ "github.com/pingcap/parser/test_driver"
)

func parse(sql string) (*ast.StmtNode, error) {
	p := parser.New()

	stmtNodes, _, err := p.Parse(sql, "", "")
	if err != nil {
		return nil, err
	}

	return &stmtNodes[0], nil
}

func main() {
	astNode, err := parse("SELECT LAG(high, 1) OVER (ORDER BY date) AS high_lag_1 FROM stocks.apple_daily;")
	if err != nil {
		fmt.Printf("parse error: %v\n", err.Error())
		return
	}
	fmt.Printf("%v\n", *astNode)
}
```

After execute the command `go run main.go`, we will get the parsing error.

```
parse error: line 1 column 26 near "(ORDER BY date) AS high_lag_1 FROM stocks.apple_daily;" 
```

**Comment by kennytm** [comment]
oh, you need to [set `EnableWindowFunc` to true](https://pkg.go.dev/github.com/pingcap/parser?tab=doc#Parser.EnableWindowFunc) to allow parsing them.

```go
func parse(sql string) (*ast.StmtNode, error) {
	p := parser.New()
	p.EnableWindowFunc(true)
```

@tangenta does it make sense to set `EnableWindowFunc` true by default nowadays? It has been set to true in TiDB since pingcap/tidb#10607 over a year ago.

**Comment by tangenta** [comment]
> @tangenta does it make sense to set EnableWindowFunc true by default nowadays?

https://github.com/pingcap/parser/blob/7de049213f00b8b550c2b19c41b40bee820e1388/lexer.go#L51-L54

If we set it true by default, there should be a TiDB config option to control this behavior.

**Comment by kennytm** [comment]
@tangenta 

```
MySQL [(none)]> select @@tidb_enable_window_function;
+-------------------------------+
| @@tidb_enable_window_function |
+-------------------------------+
| 1                             |
+-------------------------------+
1 row in set (0.001 sec)

MySQL [(none)]> select 1 row_number;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 19 near "row_number"

MySQL [(none)]> set @@tidb_enable_window_function = 0;
Query OK, 0 rows affected (0.001 sec)

MySQL [(none)]> select 1 row_number;
+------------+
| row_number |
+------------+
|          1 |
+------------+
1 row in set (0.001 sec)
```
